# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

matrix:
  allow_failures:
    - julia: nightly

jobs:
  include:
    - stage: "Test"
      julia:
        - 1.1
        - nightly
      os:
        - linux
        - osx
      script:
        - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'
      after_success:
        - if [[ $TRAVIS_JULIA_VERSION = 1.1 ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
            julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
          fi

    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

